### ISSUE TITLE
up from library document+page stays on document

### ISSUE THREAD

**Issue by cziaarm** [Transkribus/TWI-navigation#2]
library view document takes two+one arguments collId/docId[/page_num]

if page_num is present up will not go to library/collId as expected.

**Comment by cziaarm** [comment]
From @hackmanschorsch says:

And we need to think of the navigation for the edit interfaces as well. I've added links to Matti's pages and then the nav button should lead back to the browse page I guess?

**Comment by hackmanschorsch** [comment]
Not sure if this is an open issue?

**Comment by hackmanschorsch** [comment]
works fine now
